pipeline {
    agent any

    parameters {
       booleanParam(
          name: 'APPLY_TERRAFORM',
          defaultValue: false,
          description: 'Apply the approved Terraform plan to AWS'
          )
    }

    stages {

        stage('Terraform Init') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'jenkins-terraform'
                ]]) {
                    dir('terraform/environments/dev') {
                        bat 'terraform init -input=false'
                    }
                }
            }
        }

        stage('Terraform Format') {
            steps {
                bat 'terraform fmt -check -recursive terraform'
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('terraform/environments/dev') {
                    bat 'terraform validate'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'jenkins-terraform'
                ]]) {
                    dir('terraform/environments/dev') {
                        bat 'terraform plan -input=false -out=tfplan'
                    }
                }
            }
        }

	stage('Archive Terraform Plan') {
    	    steps {
        	archiveArtifacts artifacts: 'terraform/environments/dev/tfplan',
                         fingerprint: true
    		}
	}

	stage('Terraform Approval') {
    	   steps {
        	input message: 'Review the Terraform plan and approve to continue', ok: 'Approve'
    		}
	}
	
	stage('Terraform Apply') {

	   when {
        	expression {
            	params.APPLY_TERRAFORM
        	}
    	   }

    	   steps {
        	withCredentials([[
            	$class: 'AmazonWebServicesCredentialsBinding',
            	credentialsId: 'jenkins-terraform'
        	]]) {
            	dir('terraform/environments/dev') {
                bat 'terraform apply -input=false tfplan'
            	}
        	}
    	}
	}
    }
}
