pipeline {
    agent any

    stages {

        stage('Terraform Init') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'jenkins-terraform'
                ]]) {
                    dir('terraform/environments/dev') {
                        bat 'terraform init -input=false'
                    }
                }
            }
        }

        stage('Terraform Format') {
            steps {
                bat 'terraform fmt -check -recursive terraform'
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('terraform/environments/dev') {
                    bat 'terraform validate'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('terraform/environments/dev') {
                    bat 'terraform plan'
                }
            }
        }
    }
}
