pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    stages {
        stage('Build') {
            steps {
                dir('ecommerce-app') {
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('ecommerce-app') {
                    bat 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('ecommerce-app') {
                    bat 'mvn package -DskipTests'
                }
            }
        }
    }

    post {
        success {
            archiveArtifacts artifacts: 'ecommerce-app/target/*.jar',
                             fingerprint: true
        }
    }
}
