pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    stages {
        stage('Build') {
            steps {
                dir('ecommerce-app') {
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('ecommerce-app') {
                    bat 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('ecommerce-app') {
                    bat 'mvn package -DskipTests'
                }
            }
        }

	stage('Docker Test') {
            steps {
                bat 'docker version'
            }
        }

        stage('Approval') {
            steps {
                input message: 'Approve to continue?', ok: 'Approve'
            }
        }
	}

    post {
        success {
            archiveArtifacts artifacts: 'ecommerce-app/target/*.jar',
                             fingerprint: true
        }
    }
}
