pipeline {
    agent {
        label 'linux'
    }

    stages {

        stage('Verify Code') {
            steps {
                sh '''

                    echo "=== Branch ==="
                    git branch --show-current

                    echo "=== Commit ==="
                    git log -1 --oneline

                    echo "=== Jenkinsfile ==="
                    ls -l ansible-ecommerce/Jenkinsfile
                '''
            }
        }

        stage('Run Ansible') {
            steps {
                sh '''
                    cd devops-git-assignment/ansible-ecommerce

                    ansible-playbook playbooks/site.yml \
                        --vault-password-file ~/.ansible-vault-password
                '''
            }
        }
    }
}
